spring.application.name=madeinrdc

spring.datasource.url= jdbc:mysql://localhost:3306/madeinrdc_db?useSSL=false
spring.datasource.username= root
spring.datasource.password= monkila1234

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto= update


server.port= 9090
# server.address=192.168.1.79

# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=jnkiwa25@gmail.com
# spring.mail.password=Ahumba243
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB

supportNumber=+243816717846
jwtSecret = 43816717846jdjjsji43816717846jjejhjh43816717846hwjhjjhew43816717846hjjhdj43816717846
jwtExpirationMs = 86400000
jwtCookie =monkilatoken